### ISSUE TITLE
Baza

### ISSUE THREAD

**Issue by jaanos** [zigazupancic/recipes#1]
Ideja projekta je, da uporabniku ni potrebno pri sebi nameščati baze, pač pa se aplikacija poveže na bazo na baza.fmf.uni-lj.si. Za potrebe projekta uporabite eno od vaših baz `sem2017_*`, povežite pa se z uporabnikom `javnost` in geslom `javnogeslo`. Ta uporabnik naj ima seveda ravno takšne pravice, da bo mogoča uporaba aplikacije. Za ustvarjanje in polnjenje tabel se seveda povežite s svojimi uporabniškimi imeni, da boste imeli vse pravice.

**Comment by zigazupancic** [comment]
Lokalno bazo uporabljamo le v fazi razvoja, da je delo mogoče tudi brez internetne povezave in da je bilo mogoče tudi na začetku, ko baza na FMF še ni delovala.
